### ISSUE TITLE
Broken 

### ISSUE THREAD

**Issue by erdnaxeli** [ambitioninc/pip-conflict-checker#9]

**Comment by erdnaxeli** [comment]
Related to: https://github.com/pypa/pip/issues/5154

**Comment by Constantin07** [comment]
I'm getting the same issue on MacOS in venv:

pip 18.1
python 2.7.15
virtualenv==16.1.0

```
(venv) @ $ pipconflictchecker -v
Traceback (most recent call last):
  File "/Users/user/venv/bin/pipconflictchecker", line 11, in <module>
    sys.exit(main())
  File "/Users/user/venv/lib/python2.7/site-packages/pipconflictchecker/checker.py", line 279, in main
    conflicts = checker.get_conflicts()
  File "/Users/user/venv/lib/python2.7/site-packages/pipconflictchecker/checker.py", line 244, in get_conflicts
    requirement_versions = self.get_requirement_versions()
  File "Users/user/venv/lib/python2.7/site-packages/pipconflictchecker/checker.py", line 208, in get_requirement_versions
    distributions = pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'
```

**Comment by Alex-Bogdanov** [comment]
great tool for revealing conflicts! nice

**Comment by worldmind** [comment]
[Here](https://github.com/Miserlou/Zappa/issues/1471) same problem in another project and some solutions in comments.

**Comment by somewes** [comment]
this should be fixed in version 0.6.0. newer versions of pip offer the same functionality as what this project was meant to do. ```pip check```
